### ISSUE TITLE
Add host name to Dcitri v2.0 host/treatment 

### ISSUE THREAD

**Issue by suryasaha** [solgenomics/pen#9]
C medica (Citron) -  kruse 
Citrus spp - Vyas (whole body)
C Reticulate Blanco Cv. Shatangju - Wu (Abdomen, Antennae)
Citrus macrophylla

**Comment by suryasaha** [comment]
Should be C Reticulata Blanco Cv. Shatangju - Wu (Abdomen, Antennae)

**Comment by MFlores2021** [comment]
Corrected
